add files apple test

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -16,17 +16,20 @@ workflows:
       - script: flutter --version
       - script: flutter packages pub get
       - script: dart pub cache repair
-      - name: Restore GoogleService-Info.plist
+      - name: Install CocoaPods dependencies
         script: |
-          echo "$GOOGLE_SERVICE_PLIST_B64" | base64 --decode > ios/Runner/GoogleService-Info.plist
-      - name: Check GoogleService-Info.plist exists
-        script: |
-          if [ -f ios/Runner/GoogleService-Info.plist ]; then
-            echo "✅ GoogleService-Info.plist restored!"
-          else
-            echo "❌ GoogleService-Info.plist NOT found!"
-            exit 1
-          fi
+          cd ios
+          pod install
+      - name: Verifique existência do .plist
+        script: ls -l ios/Runner/GoogleService-Info.plist
+      # - name: Check GoogleService-Info.plist exists
+      #   script: |
+      #     if [ -f ios/Runner/GoogleService-Info.plist ]; then
+      #       echo "✅ GoogleService-Info.plist restored!"
+      #     else
+      #       echo "❌ GoogleService-Info.plist NOT found!"
+      #       exit 1
+      #     fi
       - name: Flutter build ipa
         script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
     artifacts:
@@ -36,7 +39,7 @@ workflows:
         auth: integration
         submit_to_app_store: true
         release_type: SCHEDULED
-        copyright: 2023 Profair
+        copyright: 2025 Profair
 
   android:
     name: Android Workflow
